code refactor for modularity

diff --git a/auto_deploy b/auto_deploy
--- a/auto_deploy
+++ b/auto_deploy
@@ -1,5 +1,5 @@
 #!/bin/bash
-declare -r intro_info="This is an Automated program to deploy mariadb Instances using Ansible"
+declare -r intro_info="This is an Automated program to deploy MariaDB and Maxscale Instances using Ansible"
 declare -r wlc_text="||*************Launching Configuration*************||"
 declare -a details_arr
 declare -A full_details
@@ -23,14 +23,6 @@ echo $intro_info
 echo
 
 #echo -e "Makes a DingSound\a"
-while getopts u:p: option; do
-	case $option in 
-		u) user=$OPTARG;;
-		p) password=$OPTARG;;
-		?) echo "unknown flag"
-	esac
-done
-#echo "user: $user / password: $password"
 printTableformat(){
     local -r delimiter="${1}"
     local -r data="$(removeEmptyLines "${2}")"
@@ -195,8 +187,6 @@ standalone_install(){
   default_version="latest"
   read -ep "Enter Mariadb version(e.g. 10.4) [$default_version]: " mariadb_version
   selected_version=${mariadb_version-$default_version}
-  #write version to variable file and use in playbook
-  sed -i "s/dbVersion/$mariadb_version/g" deploy_standalone_enterprise.yml 
 
   echo "Choose MariaDB distribution to install: "
   select edition in  "Enterprise" "Community" "quit"
@@ -204,15 +194,15 @@ do
   	case $edition in 
                 Enterprise) echo "Selected edition: Enterprise"; edition="Enterprise";;
                 Community) echo "Selected edition: Community"; edition="Community";;
-                #quit) echo "Terminating Program... Bye..."; break;;
-                *) echo "Invalid option";;
+                quit) echo "Terminating Program... Bye..."; exit 1;;
+                *) echo "Invalid option"; break;;
         esac
 	break
 done
   if [[ $edition == "Enterprise" ]]; then
-      read -p "Enter Customer key:" cust_key
+      read -p "Enter download Token:" cust_key
       #write customer token  key to config file
-      sed -i "s/custToken/$cust_key/g" deploy_standalone_enterprise.yml 
+      #sed -i "s/custToken/$cust_key/g" deploy_standalone_enterprise.yml 
   fi
 
   read -p "Enter Number of Nodes:" no_instances
@@ -289,22 +279,14 @@ start_deployment(){
   echo "[NOTE]: Initial checks passed. Proceeding to deploy on configured nodes"
   echo "[NOTE]: Ensure configured hosts are properly captured in Playbook."
   if [[ "$1" == "true" && "$2" == "Community" ]]; then
-    ansible-playbook deploy_standalone.yml -i $custom_host_file
+    ansible-playbook deploy_standalone.yml -i $custom_host_file --extra-vars "dbVersion=$selected_version"
     elif [[ "$1" == "true" && "$2" == "Enterprise" ]]; then
-    ansible-playbook deploy_standalone_enterprise.yml -i $custom_host_file
+    echo "$cust_key"
+    ansible-playbook deploy_standalone_enterprise.yml -i $custom_host_file --extra-vars "dbVersion=$selected_version download_token=$cust_key"
   elif [[ "$1" == "false" && "$2" == "Community" ]]; then
-    ansible-playbook deploy_replication.yml -i $custom_host_file
+    ansible-playbook deploy_replication.yml -i $custom_host_file --extra-vars "dbVersion=$selected_version download_token=$cust_key"
   fi
 
-   #reset config vars to default.
-   sed -i '/mariadb_version/ c\mariadb_version: "dbVersion"' deploy_standalone_enterprise.yml
-   sed -i '/customer_token/ c\customer_token: "custToken"' deploy_standalone_enterprise.yml
-
-   sed -i '/mariadb_version/ c\mariadb_version: "dbVersion"' deploy_standalone.yml
-   sed -i '/customer_token/ c\customer_token: "custToken"' deploy_standalone.yml
-
-   sed -i '/mariadb_version/ c\mariadb_version: "dbVersion"' deploy_replication.yml
-   sed -i '/customer_token/ c\customer_token: "custToken"' deploy_replication_enterprise.yml
 }
 
 check_OS(){
@@ -354,12 +336,12 @@ fi
 echo "Select one of the tasks below to proceed: "
 echo "-------------------------------------------------"
 
-select task in  "MASTER-REPLICAS" "STANDALONE_INSTANCES" "GALERA_CLUSTER" "quit"
+select task in  "MASTER-REPLICAS" "STANDALONE_INSTANCES" "MAXSCALE" "quit"
 do
 	case $task in 
 		MASTER-REPLICAS) echo "Selected task: MASTER-REPLICAS"; begin_install;;
 		STANDALONE_INSTANCES) echo "Selected task: SINGLE_INSTANCES"; standalone_install;;
-		GALERA_CLUSTER) echo "Selected task: GALERA"; break;;
+		MAXSCALE) echo "Selected task: INSTALL & CONFIGURE MAXSCALE"; break;;
                 quit) echo "Terminating Program... Bye..."; break;;
 		*) echo "Invalid option";;
 	esac
