code modified for standalone, replication & galera setup. both Enterprise and Community version

diff --git a/auto_deploy b/auto_deploy
--- a/auto_deploy
+++ b/auto_deploy
@@ -1,25 +1,27 @@
 #!/bin/bash
-set +x
+#set +x
 declare -r intro_info="This is an Automated program to deploy mariadb Instances using Ansible"
 declare -r wlc_text="||*************Launching Configuration*************||"
 declare -a details_arr
 declare -A full_details
 declare -i inst_nos
+declare edition
 #declare array to hold instance details: 
 declare -r custom_host_file="custom_deployment_hosts"
 declare -r custom_dns_file="custom_dns_file"
 declare -r inv_group_name="dbservers"
 #echo "enter username";  read uname
 #read -p "which program?" prog 
-read -s -p "Enter Password: " password
+#read -s -p "Enter Password: " password
 echo
 echo "====================================================="
 echo $wlc_text
 echo "====================================================="
-echo -e 'Written By Michael Amadi. \xc2\xa9 2022'
-printf "%(%Y-%m-%d %H:%M:%S)T\n" $(date +%s)
+#echo -e 'Starting Configuration. \xc2\xa9 2022'
+printf "Starting Configuration: %(%Y-%m-%d %H:%M:%S)T\n" $(date +%s)
 echo "**********************************************************"
-echo $intro_info
+echo $intro_info 
+echo
 
 #echo -e "Makes a DingSound\a"
 while getopts u:p: option; do
@@ -172,7 +174,7 @@ EOF
 cat >> $custom_dns_file <<-EOF
 $host  $alias
 EOF
-	#full_details+=([alias]=$alias [host]=$host [ssh_user]=$ssh_user [ssh_password]=$ssh_password)
+
    done
 echo
    printTableformat ',' "$(cat server_details)"
@@ -189,11 +191,107 @@ else
 fi
 }
 
+standalone_install(){
+  echo "Starting task..."
+  default_version="latest"
+  read -ep "Enter Mariadb version(e.g. 10.4) [$default_version]: " mariadb_version
+  selected_version=${mariadb_version-$default_version}
+  #write version to variable file and use in playbook
+
+  select edition in  "Enterprise" "Community" "quit"
+do
+  	case $edition in 
+                Enterprise) echo "Selected edition: Enterprise"; edition="Enterprise";;
+                Community) echo "Selected edition: Community"; edition="Community";;
+                quit) echo "Terminating Program... Bye..."; break;;
+                *) echo "Invalid option";;
+        esac
+	break
+done
+  if [[ $edition == "Enterprise" ]]; then
+      read -p "Enter Customer key:" cust_key
+  fi
+
+  read -p "Enter Number of Nodes:" no_instances
+if [[ $no_instances -gt 0 ]]; then 
+   #echo $?
+   #call next program
+   for ((i=1; i<=$no_instances; i++))
+   do
+	echo
+	echo "configure instance: $i"
+	#instance_details[alias]
+	read -p "alias($i): " alias
+	read -p "host($i):  " host
+	read -p "ssh_user:  " ssh_user
+	unset ssh_password
+        unset charcount        
+        unset inst_no 
+        inst_no=$i
+	charcount=0
+	prompt="ssh_password: "
+	while IFS= read -s -r -n 1 -p "$prompt" ssh_pwd
+	do
+		#take and mask password with * characters
+		if [[ $ssh_pwd == $'\0' ]]
+		then
+		   break
+		fi
+		#handle Backspaces
+		if [[ $ssh_pwd == $'\177' ]]; then
+		    if [[ $charcount -gt 0 ]]; then
+                        charcount=$((charcount-1))
+       			prompt=$'\b \b'
+		        ssh_password="${ssh_password%?}"
+                    else
+			prompt=''
+                    fi
+		else
+		    charcount=$((charcount+1))
+	            prompt='*'
+		    ssh_password+="$ssh_pwd"
+		fi
+	done
+declare redacted_pwd=${ssh_password//[a-z0-9]/x}
+cat >> server_details <<-EOF
+$inst_no,$alias,$host,$ssh_user,$redacted_pwd
+EOF
+#write custom host deployment
+cat >> $custom_host_file <<-EOF
+$alias ansible_ssh_host=$host ansible_connection=ssh ansible_user=$ssh_user ansible_password=$ssh_password
+EOF
+#write hostname to /etc/hosts
+cat >> $custom_dns_file <<-EOF
+$host  $alias
+EOF
+
+   done
+echo
+   printTableformat ',' "$(cat server_details)"
+   echo
+   read -p "Proceed with deploying to the above servers[Y/N]: "  conf_pr
+   if [[ $conf_pr = "y" || $conf_pr = "yes" ]]; then
+   	echo "Launching Auto Deploy."; launchAnsible true $edition
+   elif [[ $conf_pr = "n" || $conf_pr = "no" ]]; then
+   echo "Terminating Program... Bye..."
+   fi
+#**********
+else
+   echo "[Error] : Please enter a Number greater than 0"
+fi  
+}
+
 start_deployment(){
   echo "[NOTE]: [----------------------starting deployment----------------------]"
   echo "[NOTE]: Initial checks passed. Proceeding to deploy on configured nodes"
   echo "[NOTE]: Ensure configured hosts are properly captured in Playbook."
-  ansible-playbook dbdeploy_bk.yml -i $custom_host_file 
+  if [[ "$1" == "true" && "$2" == "Community" ]]; then
+    ansible-playbook deploy_standalone.yml -i $custom_host_file
+    elif [[ "$1" == "true" && "$2" == "Enterprise" ]]; then
+    ansible-playbook deploy_standalone_enterprise.yml -i $custom_host_file
+  elif [[ "$1" == "false" && "$2" == "Community" ]]; then
+    ansible-playbook deploy_replication.yml -i $custom_host_file
+  fi
 }
 
 check_OS(){
@@ -201,7 +299,7 @@ printf "\033[0;33mDetecting Server Architectures\033[33;5m......\033[0m\n"
 oscheck_status=$(sshpass -p $ssh_password ssh -o ConnectTimeout=5 $ssh_user@$host 'bash -s' < $(dirname "$0")/check_distro.sh)
 ansible-playbook check_os.yml -i $custom_host_file
 write_custom_resolv
-check_existingDB
+check_existingDB $1 $2
 }
 
 write_custom_resolv(){
@@ -213,7 +311,7 @@ check_existingDB(){
 echo -e "Checking DB"
 ansible-playbook check_os.yml -i $custom_host_file
 #sshpass -p $ssh_password ssh -o ConnectTimeout=5 $ssh_user@$host 'bash -s' < $(dirname "$0")/check_existing_db_service.sh
-start_deployment
+start_deployment $1 $2
 }
 
 launchAnsible(){
@@ -233,7 +331,7 @@ echo "Initiating SSH checks to target nodes..."
 ssh_status=$(sshpass -p $ssh_password ssh -o ConnectTimeout=5 $ssh_user@$host echo ok 2>&1)
 echo $ssh_status
 if [[ $ssh_status == ok ]]; then
-  echo -e "\033[0;32mssh check: passed\033[0m"; check_OS
+  echo -e "\033[0;32mssh check: passed\033[0m"; check_OS $1 $2
 else
   echo -e "\033[0;31m[Error]: ssh check: failed. Reconfirm ssh credentials or configure ssh trust\033[0m".
   echo -e  "\033[0;33mTerminating program. Fix the reported error(s) and relaunch.\033[0m"
@@ -243,14 +341,13 @@ fi
 echo "Select one of the tasks below to proceed: "
 echo "-------------------------------------------------"
 
-select task in  "INSTALL" "UPGRADE" "RESTORE" "BACKUP" "quit"
+select task in  "MASTER-REPLICAS" "STANDALONE_INSTANCES" "GALERA" "quit"
 do
 	case $task in 
-		INSTALL) echo "Selected task: INSTALL"; begin_install;;
-		UPGRADE) echo "Selected task: UPGRADE"; begin_install;;
-		RESTORE) echo "Selected task: RESTORE"; begin_install;;
-		BACKUP) echo "Selected task: BACKUP"; begin_install;;
-                quit) break;;
+		MASTER-REPLICAS) echo "Selected task: MASTER-REPLICAS"; begin_install;;
+		STANDALONE_INSTANCES) echo "Selected task: SINGLE_INSTANCES"; standalone_install;;
+		GALERA) echo "Selected task: GALERA"; begin_install;;
+                quit) echo "Terminating Program... Bye..."; break;;
 		*) echo "Invalid option";;
 	esac
 	break
